java.lang.NullPointerException: Cannot invoke "no.nav.system.os.tjenester.simulerfpservice.simulerfpserviceservicetypes.SimulerBeregningResponse.getSimulering()" because "response" is null 	at urskog.SimuleringMapperV1Kt.intoV1(SimuleringMapperV1.kt:14)
Co-authored-by: anders skifte <anders.skifte@nav.no>
Co-authored-by: robin tordly <robin.tordly@nav.no>
Co-authored-by: trond inge lillesand <trond.inge.lillesand@nav.no>
Signed-off-by: JorgenNyb <201098578+JorgenNyb@users.noreply.github.com>